/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Public__rootIndexRouteImport } from './routes/_public__root/index'

const Public__rootIndexRoute = Public__rootIndexRouteImport.update({
  id: '/_public__root/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof Public__rootIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof Public__rootIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public__root/': typeof Public__rootIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_public__root/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Public__rootIndexRoute: typeof Public__rootIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public__root/': {
      id: '/_public__root/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Public__rootIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Public__rootIndexRoute: Public__rootIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
