/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Public__rootRouteRouteImport } from './routes/_public__root/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as Public__rootIndexRouteImport } from './routes/_public__root/index'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as Public__rootTarifsIndexRouteImport } from './routes/_public__root/tarifs/index'
import { Route as Public__rootReservationIndexRouteImport } from './routes/_public__root/reservation/index'
import { Route as Public__rootMentionsLegalesIndexRouteImport } from './routes/_public__root/mentions-legales/index'
import { Route as Public__rootGalerieIndexRouteImport } from './routes/_public__root/galerie/index'
import { Route as Public__rootContactIndexRouteImport } from './routes/_public__root/contact/index'
import { Route as Public__rootCgvIndexRouteImport } from './routes/_public__root/cgv/index'
import { Route as AuthenticatedMonCompteIndexRouteImport } from './routes/_authenticated/mon-compte/index'
import { Route as AuthInscriptionIndexRouteImport } from './routes/_auth/inscription/index'
import { Route as AuthConnexionIndexRouteImport } from './routes/_auth/connexion/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as ApiWebhooksPolarRouteImport } from './routes/api/webhooks/polar'

const Public__rootRouteRoute = Public__rootRouteRouteImport.update({
  id: '/_public__root',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const Public__rootIndexRoute = Public__rootIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Public__rootRouteRoute,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const Public__rootTarifsIndexRoute = Public__rootTarifsIndexRouteImport.update({
  id: '/tarifs/',
  path: '/tarifs/',
  getParentRoute: () => Public__rootRouteRoute,
} as any)
const Public__rootReservationIndexRoute =
  Public__rootReservationIndexRouteImport.update({
    id: '/reservation/',
    path: '/reservation/',
    getParentRoute: () => Public__rootRouteRoute,
  } as any)
const Public__rootMentionsLegalesIndexRoute =
  Public__rootMentionsLegalesIndexRouteImport.update({
    id: '/mentions-legales/',
    path: '/mentions-legales/',
    getParentRoute: () => Public__rootRouteRoute,
  } as any)
const Public__rootGalerieIndexRoute =
  Public__rootGalerieIndexRouteImport.update({
    id: '/galerie/',
    path: '/galerie/',
    getParentRoute: () => Public__rootRouteRoute,
  } as any)
const Public__rootContactIndexRoute =
  Public__rootContactIndexRouteImport.update({
    id: '/contact/',
    path: '/contact/',
    getParentRoute: () => Public__rootRouteRoute,
  } as any)
const Public__rootCgvIndexRoute = Public__rootCgvIndexRouteImport.update({
  id: '/cgv/',
  path: '/cgv/',
  getParentRoute: () => Public__rootRouteRoute,
} as any)
const AuthenticatedMonCompteIndexRoute =
  AuthenticatedMonCompteIndexRouteImport.update({
    id: '/mon-compte/',
    path: '/mon-compte/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthInscriptionIndexRoute = AuthInscriptionIndexRouteImport.update({
  id: '/inscription/',
  path: '/inscription/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthConnexionIndexRoute = AuthConnexionIndexRouteImport.update({
  id: '/connexion/',
  path: '/connexion/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiWebhooksPolarRoute = ApiWebhooksPolarRouteImport.update({
  id: '/api/webhooks/polar',
  path: '/api/webhooks/polar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/checkout': typeof ApiCheckoutRoute
  '/': typeof Public__rootIndexRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/admin': typeof AdminAdminIndexRoute
  '/connexion': typeof AuthConnexionIndexRoute
  '/inscription': typeof AuthInscriptionIndexRoute
  '/mon-compte': typeof AuthenticatedMonCompteIndexRoute
  '/cgv': typeof Public__rootCgvIndexRoute
  '/contact': typeof Public__rootContactIndexRoute
  '/galerie': typeof Public__rootGalerieIndexRoute
  '/mentions-legales': typeof Public__rootMentionsLegalesIndexRoute
  '/reservation': typeof Public__rootReservationIndexRoute
  '/tarifs': typeof Public__rootTarifsIndexRoute
}
export interface FileRoutesByTo {
  '/api/checkout': typeof ApiCheckoutRoute
  '/': typeof Public__rootIndexRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/admin': typeof AdminAdminIndexRoute
  '/connexion': typeof AuthConnexionIndexRoute
  '/inscription': typeof AuthInscriptionIndexRoute
  '/mon-compte': typeof AuthenticatedMonCompteIndexRoute
  '/cgv': typeof Public__rootCgvIndexRoute
  '/contact': typeof Public__rootContactIndexRoute
  '/galerie': typeof Public__rootGalerieIndexRoute
  '/mentions-legales': typeof Public__rootMentionsLegalesIndexRoute
  '/reservation': typeof Public__rootReservationIndexRoute
  '/tarifs': typeof Public__rootTarifsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public__root': typeof Public__rootRouteRouteWithChildren
  '/api/checkout': typeof ApiCheckoutRoute
  '/_public__root/': typeof Public__rootIndexRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_auth/connexion/': typeof AuthConnexionIndexRoute
  '/_auth/inscription/': typeof AuthInscriptionIndexRoute
  '/_authenticated/mon-compte/': typeof AuthenticatedMonCompteIndexRoute
  '/_public__root/cgv/': typeof Public__rootCgvIndexRoute
  '/_public__root/contact/': typeof Public__rootContactIndexRoute
  '/_public__root/galerie/': typeof Public__rootGalerieIndexRoute
  '/_public__root/mentions-legales/': typeof Public__rootMentionsLegalesIndexRoute
  '/_public__root/reservation/': typeof Public__rootReservationIndexRoute
  '/_public__root/tarifs/': typeof Public__rootTarifsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/checkout'
    | '/'
    | '/api/webhooks/polar'
    | '/admin'
    | '/connexion'
    | '/inscription'
    | '/mon-compte'
    | '/cgv'
    | '/contact'
    | '/galerie'
    | '/mentions-legales'
    | '/reservation'
    | '/tarifs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/checkout'
    | '/'
    | '/api/webhooks/polar'
    | '/admin'
    | '/connexion'
    | '/inscription'
    | '/mon-compte'
    | '/cgv'
    | '/contact'
    | '/galerie'
    | '/mentions-legales'
    | '/reservation'
    | '/tarifs'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_authenticated'
    | '/_public__root'
    | '/api/checkout'
    | '/_public__root/'
    | '/api/webhooks/polar'
    | '/_admin/admin/'
    | '/_auth/connexion/'
    | '/_auth/inscription/'
    | '/_authenticated/mon-compte/'
    | '/_public__root/cgv/'
    | '/_public__root/contact/'
    | '/_public__root/galerie/'
    | '/_public__root/mentions-legales/'
    | '/_public__root/reservation/'
    | '/_public__root/tarifs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  Public__rootRouteRoute: typeof Public__rootRouteRouteWithChildren
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiWebhooksPolarRoute: typeof ApiWebhooksPolarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public__root': {
      id: '/_public__root'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Public__rootRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public__root/': {
      id: '/_public__root/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Public__rootIndexRouteImport
      parentRoute: typeof Public__rootRouteRoute
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public__root/tarifs/': {
      id: '/_public__root/tarifs/'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof Public__rootTarifsIndexRouteImport
      parentRoute: typeof Public__rootRouteRoute
    }
    '/_public__root/reservation/': {
      id: '/_public__root/reservation/'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof Public__rootReservationIndexRouteImport
      parentRoute: typeof Public__rootRouteRoute
    }
    '/_public__root/mentions-legales/': {
      id: '/_public__root/mentions-legales/'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof Public__rootMentionsLegalesIndexRouteImport
      parentRoute: typeof Public__rootRouteRoute
    }
    '/_public__root/galerie/': {
      id: '/_public__root/galerie/'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof Public__rootGalerieIndexRouteImport
      parentRoute: typeof Public__rootRouteRoute
    }
    '/_public__root/contact/': {
      id: '/_public__root/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof Public__rootContactIndexRouteImport
      parentRoute: typeof Public__rootRouteRoute
    }
    '/_public__root/cgv/': {
      id: '/_public__root/cgv/'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof Public__rootCgvIndexRouteImport
      parentRoute: typeof Public__rootRouteRoute
    }
    '/_authenticated/mon-compte/': {
      id: '/_authenticated/mon-compte/'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof AuthenticatedMonCompteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_auth/inscription/': {
      id: '/_auth/inscription/'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof AuthInscriptionIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/connexion/': {
      id: '/_auth/connexion/'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof AuthConnexionIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/webhooks/polar': {
      id: '/api/webhooks/polar'
      path: '/api/webhooks/polar'
      fullPath: '/api/webhooks/polar'
      preLoaderRoute: typeof ApiWebhooksPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthConnexionIndexRoute: typeof AuthConnexionIndexRoute
  AuthInscriptionIndexRoute: typeof AuthInscriptionIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthConnexionIndexRoute: AuthConnexionIndexRoute,
  AuthInscriptionIndexRoute: AuthInscriptionIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMonCompteIndexRoute: typeof AuthenticatedMonCompteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMonCompteIndexRoute: AuthenticatedMonCompteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface Public__rootRouteRouteChildren {
  Public__rootIndexRoute: typeof Public__rootIndexRoute
  Public__rootCgvIndexRoute: typeof Public__rootCgvIndexRoute
  Public__rootContactIndexRoute: typeof Public__rootContactIndexRoute
  Public__rootGalerieIndexRoute: typeof Public__rootGalerieIndexRoute
  Public__rootMentionsLegalesIndexRoute: typeof Public__rootMentionsLegalesIndexRoute
  Public__rootReservationIndexRoute: typeof Public__rootReservationIndexRoute
  Public__rootTarifsIndexRoute: typeof Public__rootTarifsIndexRoute
}

const Public__rootRouteRouteChildren: Public__rootRouteRouteChildren = {
  Public__rootIndexRoute: Public__rootIndexRoute,
  Public__rootCgvIndexRoute: Public__rootCgvIndexRoute,
  Public__rootContactIndexRoute: Public__rootContactIndexRoute,
  Public__rootGalerieIndexRoute: Public__rootGalerieIndexRoute,
  Public__rootMentionsLegalesIndexRoute: Public__rootMentionsLegalesIndexRoute,
  Public__rootReservationIndexRoute: Public__rootReservationIndexRoute,
  Public__rootTarifsIndexRoute: Public__rootTarifsIndexRoute,
}

const Public__rootRouteRouteWithChildren =
  Public__rootRouteRoute._addFileChildren(Public__rootRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  Public__rootRouteRoute: Public__rootRouteRouteWithChildren,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiWebhooksPolarRoute: ApiWebhooksPolarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
